version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
  user-management-service:
    build: './user-management-service'
    restart: always
    environment:
      - REDIS_HOST=${REDDIT_HOST}
    depends_on:
      - rabbitmq
    command: ${CONTAINER_COMMAND_NODE}
  api:
    build: './api'
    restart: always
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=${REDDIT_HOST}
    depends_on:
      - rabbitmq
    command: ${CONTAINER_COMMAND_NODE}
volumes:
  rabbitmq_data:
    driver: local
