version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
  api:
    build: './api'
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
    command: ${CONTAINER_COMMAND_NODE}
    environment:
      AMQ_HOST: rabbitmq
  user-management-service:
    build: './user-management-service'
    restart: always
    depends_on:
      - rabbitmq
    command: ${CONTAINER_COMMAND_NODE}
    environment:
      AMQ_HOST: rabbitmq
      AMQ_USER: user_service
      AMQ_PASSWORD: user_service
  media-service:
    build: './media-service'
    restart: always
    depends_on:
      - rabbitmq
      - ms-mongodb
    command: ${CONTAINER_COMMAND_NODE}
    environment:
      AMQ_HOST: rabbitmq
      AMQ_USER: media_service
      AMQ_PASSWORD: media_service
  ms-mongodb:
    image: mongo
    volumes:
     - "/var/lib/ms-mongodb:/data/db"
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  rabbitmq_data:
    driver: local
